import { motion } from 'framer-motion';
import { ArrowRight, Clock3, Search, ShieldCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { usePublishedBlogs } from '@/hooks/usePublishedBlogs';
import { PageTransition } from '@/components/ui/PageTransition';
import { SectionEyebrow } from '@/components/ui/SectionEyebrow';
import { Reveal } from '@/components/ui/Reveal';
import { Testimonials } from '@/components/sections/Testimonials';
import { CtaSection } from '@/components/sections/CtaSection';
import { SiteFooter } from '@/components/layout/SiteFooter';

export function BlogPage(){const blogPosts=usePublishedBlogs();const[query,setQuery]=useState('');const posts=useMemo(()=>blogPosts.filter(p=>(p.title+p.category+p.excerpt).toLowerCase().includes(query.toLowerCase())),[blogPosts,query]);const featured=blogPosts[0];return <PageTransition>
  <section className="figma-grid bg-white"><div className="site-container grid min-h-[521px] items-center gap-10 py-16 lg:grid-cols-[640px_1fr]"><motion.div initial={{opacity:0,x:-415}} animate={{opacity:1,x:0}} transition={{duration:.5,ease:'easeOut'}} className="mx-auto w-full max-w-[620px] text-left"><div className="flex justify-start"><SectionEyebrow>ZIPLIN KNOWLEDGE HUB</SectionEyebrow></div><h1 className="mt-6 font-display text-[52px] leading-[1.15] text-ziplin-navy">Insights & <span className="text-ziplin-yellow">Resources</span></h1><p className="mt-8 max-w-[640px] text-[20px] leading-[1.35] text-[#4e5260]">Actionable tips, industry deep-dives, and guides to help your teams share secure files and coordinate growth seamlessly.</p><div className="mt-10 flex max-w-[620px] items-center gap-3 rounded-xl border bg-white px-4 py-3 shadow-sm"><Search className="size-5 text-ziplin-blue"/><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 outline-none" placeholder="Search articles and topics..."/></div></motion.div><motion.div initial={{opacity:0,x:1100}} animate={{opacity:1,x:0}} transition={{duration:.5,ease:'easeOut'}} className="relative mx-auto h-[381px] w-[391px] max-w-full overflow-hidden"><img src="/figma-assets/feature-mascot-sheet.png" alt="Ziplin mascot reading the latest blog" className="absolute left-[-962px] top-[-699px] h-[1321px] w-[1448px] max-w-none"/></motion.div></div></section>
  <section className="site-container py-20"><Reveal><Link to={`/blog/${featured.slug}`} className="group grid overflow-hidden rounded-[24px] border-2 border-[#0a0e1a] bg-white shadow-[12px_12px_0_#f4b400] lg:grid-cols-[.95fr_1.05fr]"><div className="relative min-h-[360px] overflow-hidden bg-[#0a2650]"><div className="absolute inset-0 opacity-60 [background-image:linear-gradient(rgba(66,145,230,.18)_1px,transparent_1px),linear-gradient(90deg,rgba(66,145,230,.18)_1px,transparent_1px)] [background-size:32px_32px]"/><div className="absolute inset-[12%] rounded-[28px] border border-[#4d83bf] bg-[#071b39] shadow-[0_0_60px_rgba(22,75,183,.35)]"><div className="absolute left-1/2 top-1/2 flex size-32 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-[34px] border-[12px] border-[#3173b9] text-[#ffc60a]"><ShieldCheck className="size-16"/></div></div></div><div className="flex flex-col justify-center p-8 sm:p-10"><div className="flex flex-wrap items-center gap-3 text-xs text-[#7b8598]"><span className="rounded-md bg-[#eef3ff] px-3 py-1 font-mono font-bold text-ziplin-blue">{featured.category}</span><span>{featured.date}</span><span>•</span><span>{featured.readTime}</span></div><h2 className="mt-5 font-display text-[34px] leading-[1.18] group-hover:text-ziplin-blue sm:text-[42px]">{featured.title}</h2><p className="mt-5 text-base leading-7 text-[#66718a]">{featured.excerpt}</p><div className="mt-6 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-[#edf2fa] font-semibold text-ziplin-blue">ZH</span><span><strong className="block text-sm">{featured.author}</strong><small className="text-[#8590a2]">{featured.role}</small></span></div><span className="inline-flex items-center gap-2 text-sm text-ziplin-blue">Read Article <ArrowRight className="size-4 transition group-hover:translate-x-1"/></span></div></div></Link></Reveal></section>
  <section className="site-container pb-20"><Reveal className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><SectionEyebrow>ALL ARTICLES</SectionEyebrow><h2 className="display-2 mt-5">Latest from <span className="text-ziplin-yellow">Ziplin</span></h2></div><p className="text-sm text-[#748095]">{posts.length} articles</p></Reveal><div className="mt-10 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{posts.map((post,index)=><Reveal key={post.slug} delay={index*.05}><Link to={`/blog/${post.slug}`} className="group flex h-full flex-col overflow-hidden rounded-[20px] border border-[#dce4ef] bg-white shadow-[0_12px_38px_rgba(8,28,69,.08)] transition hover:-translate-y-2"><div className={`relative h-48 overflow-hidden ${['bg-[#dfeeff]','bg-[#fff0c4]','bg-[#e9f9ef]'][index%3]}`}><div className="absolute inset-0 figma-grid-fine"/><span className="absolute left-5 top-5 rounded-md bg-white px-3 py-1 font-mono text-[10px] font-bold text-ziplin-blue shadow-sm">{post.category}</span><div className="absolute bottom-5 right-5 flex size-16 items-center justify-center rounded-2xl border-2 border-ziplin-navy bg-white text-ziplin-yellow"><ArrowRight className="size-7 -rotate-45 transition group-hover:rotate-0"/></div></div><div className="flex flex-1 flex-col p-6"><div className="flex items-center gap-2 text-xs text-[#7a8599]"><Clock3 className="size-4"/>{post.readTime}<span>•</span>{post.date}</div><h3 className="mt-4 font-display text-2xl leading-tight">{post.title}</h3><p className="mt-4 flex-1 text-sm leading-6 text-[#68738a]">{post.excerpt}</p><span className="mt-6 text-sm font-semibold text-ziplin-blue">Read article →</span></div></Link></Reveal>)}</div>{posts.length===0?<div className="py-16 text-center text-[#66718a]">No article matched “{query}”.</div>:null}</section>
  <Testimonials/><CtaSection/><SiteFooter/>
</PageTransition>}
