import { Check, ChevronDown, Clock3, ShieldCheck } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { PageTransition } from '@/components/ui/PageTransition';
import { SectionEyebrow } from '@/components/ui/SectionEyebrow';
import { Button } from '@/components/ui/Button';
import { LogoStrip } from '@/components/sections/LogoStrip';
import { SiteFooter } from '@/components/layout/SiteFooter';

export function DemoPage(){const[submitted,setSubmitted]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setSubmitted(true)};return <PageTransition>
  <section className="figma-grid min-h-[840px] bg-[#f7fbff] py-16 sm:py-20"><div className="site-container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-start"><div className="pt-10"><SectionEyebrow>LIVE DEMONSTRATION</SectionEyebrow><h1 className="display-1 mt-7 max-w-[590px]">See how Ziplin brings every <span className="text-ziplin-yellow">customer journey together</span></h1><p className="mt-6 max-w-[570px] text-lg leading-8 text-[#606a80]">Discover how comprehensive link management and tracking can streamline marketing workflows, improve campaign performance, and provide clear, actionable insights.</p><div className="mt-9 space-y-6">{[['Tailored walkthrough','A session shaped around your team size, industry, and current stack.'],['Data privacy insights','See how branded domains, UTMs, controls, and secure routing work together.'],['Q&A session','Get immediate answers from a product specialist.']].map(([title,text])=><div key={title} className="flex gap-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-[#eaf0ff] text-ziplin-blue"><Check className="size-5"/></span><div><strong className="block font-display text-xl">{title}</strong><p className="mt-1 text-sm leading-6 text-[#707a8f]">{text}</p></div></div>)}</div></div><div className="rounded-[22px] border border-[#d5deeb] bg-white shadow-[0_20px_70px_rgba(8,28,69,.15)]"><div className="h-2 rounded-t-[22px] bg-ziplin-yellow"/>{submitted?<div className="flex min-h-[560px] flex-col items-center justify-center p-8 text-center"><span className="flex size-20 items-center justify-center rounded-full bg-[#eafaf0] text-[#12a556]"><Check className="size-10"/></span><h2 className="mt-6 font-display text-3xl">Demo request received</h2><p className="mt-3 max-w-[430px] text-base leading-7 text-[#68738a]">A Ziplin specialist will contact you to confirm the selected date, time, and agenda.</p><Button onClick={()=>setSubmitted(false)} className="mt-7">Submit another request</Button></div>:<form onSubmit={submit} className="p-7 sm:p-10"><h2 className="font-display text-3xl">Schedule your demo</h2><p className="mt-3 text-sm text-[#69748a]">Fill out the details below and we’ll be in touch shortly.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><Input label="First Name" placeholder="Jane"/><Input label="Last Name" placeholder="Doe"/><Input label="Work Email" type="email" placeholder="jane@company.com" className="sm:col-span-2"/><Select label="Select slot date" options={['DD-MM-YY','18-08-2026','19-08-2026','20-08-2026']} className="sm:col-span-2"/><Select label="Select slot time" options={['Select availability time','10:00 AM IST','2:00 PM IST','5:00 PM IST']} className="sm:col-span-2"/></div><Button type="submit" size="lg" className="mt-7 w-full">Schedule Demo →</Button><p className="mt-5 text-center text-[11px] text-[#8a94a7]">By submitting, you agree to our Terms and Privacy Policy.</p></form>}</div></div></section>
  <LogoStrip/><SiteFooter/>
</PageTransition>}

function Input({label,className='',...props}:{label:string;className?:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className={`text-xs text-[#59647a] ${className}`}>{label}<input required {...props} className="mt-2 h-12 w-full rounded-lg border border-[#d7dfeb] bg-[#f3f6fb] px-4 text-sm"/></label>}
function Select({label,options,className=''}:{label:string;options:string[];className?:string}){return <label className={`relative text-xs text-[#59647a] ${className}`}>{label}<select required className="mt-2 h-12 w-full appearance-none rounded-lg border border-[#d7dfeb] bg-[#f3f6fb] px-4 text-sm">{options.map(x=><option key={x}>{x}</option>)}</select><ChevronDown className="pointer-events-none absolute bottom-3.5 right-4 size-4 text-[#738098]"/></label>}
