import { FileCheck2, LockKeyhole, Scale, ShieldCheck } from 'lucide-react';
import { Navigate, useLocation } from 'react-router-dom';
import { PageTransition } from '@/components/ui/PageTransition';
import { privacySections, termsSections } from '@/data/legal';
import { SectionEyebrow } from '@/components/ui/SectionEyebrow';
import { SiteFooter } from '@/components/layout/SiteFooter';

export function LegalPage(){const location=useLocation();const privacy=location.pathname.includes('privacy');const sections=privacy?privacySections:termsSections;const title=privacy?'Privacy Policy':'Terms and Services';const Icon=privacy?ShieldCheck:Scale;return <PageTransition>
  <section className="figma-grid bg-[#f7fbff] py-16 sm:py-20"><div className="site-container"><div className="mx-auto max-w-[1120px] rounded-[26px] border border-[#dce4ef] bg-white p-8 shadow-[0_22px_70px_rgba(8,28,69,.12)] sm:p-12"><div className="grid items-center gap-8 lg:grid-cols-[1fr_270px]"><div><SectionEyebrow>{privacy?'PRIVACY & DATA':'LEGAL TERMS'}</SectionEyebrow><h1 className="display-1 mt-7">{title}</h1><p className="mt-5 max-w-[700px] text-lg leading-8 text-[#66718a]">{privacy?'How Ziplin collects, uses, safeguards, and gives you control over information.':'The rules and responsibilities that apply when you create an account, manage a workspace, or use Ziplin services.'}</p><div className="mt-6 flex flex-wrap gap-4 text-sm text-[#7a8599]"><span>Effective: August 12, 2026</span><span>•</span><span>Last updated: August 12, 2026</span></div></div><div className="flex h-[220px] items-center justify-center rounded-[24px] bg-ziplin-navy text-ziplin-yellow"><Icon className="size-28"/></div></div></div></div></section>
  <section className="site-container py-16 sm:py-20"><div className="mx-auto grid max-w-[1120px] gap-12 lg:grid-cols-[260px_1fr]"><aside><div className="sticky top-[112px] rounded-[18px] border border-[#dce4ef] bg-white p-5 shadow-sm"><strong className="font-display text-xl">Contents</strong><nav className="mt-5 space-y-2">{sections.map((section,index)=><a key={section.title} href={`#legal-${index}`} className="block rounded-lg px-3 py-2 text-sm leading-5 text-[#68738a] hover:bg-[#f3f6fb] hover:text-ziplin-blue">{section.title}</a>)}</nav><div className="mt-6 rounded-xl bg-[#fff7d8] p-4 text-xs leading-5 text-[#5f6573]"><LockKeyhole className="mb-2 size-5 text-ziplin-yellow"/>Questions can be submitted through the contact page.</div></div></aside><article className="min-w-0"><div className="rounded-[18px] border-l-4 border-ziplin-yellow bg-[#fffaf0] p-6 text-base leading-7 text-[#5e6677]">This document is frontend design content and should be reviewed by qualified legal counsel before production publication.</div><div className="mt-10 space-y-14">{sections.map((section,index)=><section id={`legal-${index}`} key={section.title} className="scroll-mt-28"><h2 className="font-display text-3xl text-ziplin-navy">{section.title}</h2><div className="mt-5 space-y-5">{section.paragraphs.map(paragraph=><p key={paragraph} className="text-lg leading-8 text-[#596378]">{paragraph}</p>)}</div>{index===2?<div className="mt-7 grid gap-4 sm:grid-cols-2">{[['Essential controls','Authentication, session continuity, security, and core preferences.'],['Optional controls','Analytics and marketing technologies where permission and law allow.']].map(([heading,body])=><div key={heading} className="rounded-[16px] border border-[#dce4ef] bg-[#f8fbff] p-5"><FileCheck2 className="size-5 text-ziplin-yellow"/><strong className="mt-3 block">{heading}</strong><p className="mt-2 text-sm leading-6 text-[#69748a]">{body}</p></div>)}</div>:null}</section>)}</div></article></div></section><SiteFooter/>
</PageTransition>}

export function LegalRedirect(){return <Navigate to="/privacy" replace/>}
